name: Lint and spell check
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Install Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        # Update output format to enable automatic inline annotations.
        - name: Ruff Check
          run: ruff check --output-format=github .

        - uses: codespell-project/actions-codespell@v2
